# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Pieter Germishuys
tagline: "Software Development"
description: 'It's not about the destination, but the journey'
url: https://blog.pieterg.com
baseurl: /

author:
  name: "Mark Otto"
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/pgermishuys
